### ISSUE TITLE
spark-rapids script is not updated in the gcs bucket

### ISSUE THREAD

**Issue by nvliyuan** [GoogleCloudDataproc/initialization-actions#1054]
Since the [script](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/spark-rapids/spark-rapids.sh) has been updated by [pr](https://github.com/GoogleCloudDataproc/initialization-actions/pull/1046), the script in gcs should also be kept in sync : `gs://goog-dataproc-initialization-actions-${REGION}/spark-rapids/spark-rapids.sh`.

**Comment by nvliyuan** [comment]
@jayadeep-jayaraman could you help check?

**Comment by jayadeep-jayaraman** [comment]
Hi @nvliyuan - the release is planned for this week. Will keep you posted.

**Comment by nvliyuan** [comment]
Thanks @jayadeep-jayaraman , when do we normally update(release)? maybe I could add this info in [readme](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/spark-rapids/README.md) so that users could know

**Comment by jayadeep-jayaraman** [comment]
it usually takes 2-3 weeks from the time we merge the changes

**Comment by nvliyuan** [comment]
Is the 2-3 week period calculated from the merge of this [pr](https://github.com/GoogleCloudDataproc/initialization-actions/pull/1046)?

**Comment by jayadeep-jayaraman** [comment]
yes, usually we follow that window. This time there were few other changes hence it got delayed by a couple of weeks

**Comment by cjac** [comment]
@nvliyuan - is the bucket updated correctly now?

**Comment by nvliyuan** [comment]
Hi @cjac , seems the bucket is still not updated, the plugin version is still v23.02, it should be v23.04:
```
(base) yuanli@yuanli-System-Product-Name:~/work$ gsutil cat gs://goog-dataproc-initialization-actions-us-central1/spark-rapids/spark-rapids.sh


Updates are available for some Google Cloud CLI components.  To install them,
please run:
  $ gcloud components update

#!/bin/bash

set -euxo pipefail

function get_metadata_attribute() {
  local -r attribute_name=$1
  local -r default_value=$2
  /usr/share/google/get_metadata_value "attributes/${attribute_name}" || echo -n "${default_value}"
}

OS_NAME=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
readonly OS_NAME

readonly SPARK_VERSION_ENV=$(spark-submit --version 2>&1 | sed -n 's/.*version[[:blank:]]\+\([0-9]\+\.[0-9]\).*/\1/p' | head -n1)
readonly DEFAULT_SPARK_RAPIDS_VERSION="23.02.0"
```

**Comment by cjac** [comment]
Okay.  I think there's a command I can run to flush the changes.  I'll try
to remember to do that on Monday.  I have a change in working on fire the
connectors, so I think I'll get that one done first and then push it all.

**Comment by jayadeep-jayaraman** [comment]
Let me check the release status and get back to you on this.

**Comment by cjac** [comment]
I've confirmed that the version is now 23.06.0
