### ISSUE TITLE
connectors.sh does not work on 2.1-debian11 image

### ISSUE THREAD

**Issue by cjac** [GoogleCloudDataproc/initialization-actions#1062]
```
cjac@cluster-1668020639-m:~$ gsutil ls -l gs://hadoop-lib/hive-bigquery/hive-bigquery-connector-2.0.1-preview.jar
AccessDeniedException: 403 sa-cluster-1668020639@REDACTED.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
```

It sounds like it's talking about the bucket **gs://hadoop-lib**

```
$ gsutil ls -l gs://hadoop-lib/hive-bigquery/hive-bigquery-connector-2.0.1-preview.jar
AccessDeniedException: 403 cjac@colliertech.org does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
```

**Comment by cjac** [comment]
Fixed with #1063

**Comment by cjac** [comment]
Not quite fixed with 1063.  We need support for scala 2.13 ; I'll propose a patch

**Comment by cjac** [comment]
related patch in #1064

**Comment by khaledh** [comment]
@cjac Thanks for the fix! When should I expect this to be deployed to the GCS bucket? I checked `gs://goog-dataproc-initialization-actions-us-central1/connectors/connectors.sh` but it seems it's still the old version.

**Comment by cjac** [comment]
It takes some time before a copy is automatically.  Read the README.md in the root folder for best practices.  I have another couple fixes to get in to initialization-actions, then I can manually trigger a push to gcs.  It may be a couple of weeks, so do read the root README.md for how to handle things until then.

**Comment by khaledh** [comment]
@cjac Thanks. We've copied the script to a private bucket.

**Comment by cjac** [comment]
merged
