### ISSUE TITLE
Missing linux headers on debian dataproc instances after update

### ISSUE THREAD

**Issue by SurajAralihalli** [GoogleCloudDataproc/initialization-actions#1084]
**Error**:
E: Unable to locate package linux-headers-5.10.0-24-cloud-amd64

**Steps to reproduce**:

1. Create a dataproc instance with Debian image (2.0 or 2.1)
2. Run `apt-get update`
3. Run `apt-get install -y -q linux-headers-$(uname -r)` which is `install -y -q linux-headers-5.10.0-24-cloud-amd64`

**Note**: 
This error is not observed if `linux-headers-5.10.0-24-cloud-amd64` is installed before running `apt-get update`

**Comment by viadea** [comment]
@jayadeep-jayaraman  can you take a look at this one?thx

**Comment by nvliyuan** [comment]
I could reproduce same issue:
![image](https://github.com/GoogleCloudDataproc/initialization-actions/assets/84758614/d9240e6c-b2fd-40ab-8824-b5ee6ea7527d)

**Comment by functicons** [comment]
It seems that `linux-headers-5.10.0-24-cloud-amd64` was removed from the apt repo. You might need to specify `5.10.0-24-cloud-amd64` explicitly as a workaround. Is this issue related to any init actions?

**Comment by SurajAralihalli** [comment]
Yes, this is part of init actions for starting a debian instance with spark rapids plugin. 

`You might need to specify 5.10.0-24-cloud-amd64 explicitly as a workaround` Can we fetch this dependency from some other source? 

cc: @nvliyuan @viadea

**Comment by viadea** [comment]
@functicons  @jayadeep-jayaraman 
Is this issue fixed already?  

Will we have a permanent fix instead of a workaround?

**Comment by SurajAralihalli** [comment]
Closing it as the `linux-headers-5.10.0-24-cloud-amd64` linux headers are now available on Debian dataproc instances. This unblock setting up the spark rapids plugin using init script.
