### ISSUE TITLE
Error on wget livy binary naming

### ISSUE THREAD

**Issue by saimaung** [GoogleCloudDataproc/initialization-actions#1104]
Getting the following error:

```sh
wget -nv --timeout=30 --tries=5 --retry-connrefused https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating_2.11-bin.zip -P /tmp/livy-init-action-scta
https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating_2.11-bin.zip:
2023-10-22 01:38:19 ERROR 404: Not Found.
```

Based on the apache archive, scala version isn't a part of the bin naming for livy version less than 0.8.0:
https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/

Example:

```sh
[apache-livy-0.7.1-incubating-bin.zip](https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating-bin.zip)        2021-02-04 05:00   88M  
[TXT] [apache-livy-0.7.1-incubating-bin.zip.asc](https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating-bin.zip.asc)    2021-02-04 05:00  801   
[TXT] [apache-livy-0.7.1-incubating-bin.zip.sha512](https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating-bin.zip.sha512) 2021-02-04 05:00  296   
[   ] [apache-livy-0.7.1-incubating-src.zip](https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating-src.zip)        2021-02-04 05:00  1.1M  
[TXT] [apache-livy-0.7.1-incubating-src.zip.asc](https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating-src.zip.asc)    2021-02-04 05:00  801   
[TXT] [apache-livy-0.7.1-incubating-src.zip.sha512](https://archive.apache.org/dist/incubator/livy/0.7.1-incubating/apache-livy-0.7.1-incubating-src.zip.sha512) 2021-02-04 05:00  296
```

**Comment by cjac** [comment]
Thanks for the report.  I'll have @erickmunz take a look at it.

**Comment by cjac** [comment]
I understand that we've got a high priority issue blocking on this problem.  This issue could have been avoided had the instructions in the README been followed:

⚠️ NOTICE: For production usage, before creating clusters, it is strongly recommended that you copy initialization actions to your own Cloud Storage bucket to guarantee consistent use of the same initialization action code across all Dataproc cluster nodes and to prevent unintended upgrades from upstream in the cluster

The previous version can be found at

https://github.com/GoogleCloudDataproc/initialization-actions/blob/0946a9c7ecf7defafea8a48617ffe493ed344491/livy/livy.sh

I am developing the fix in #1106 

You can fetch a pre-release from my github repo at:

https://raw.githubusercontent.com/cjac/initialization-actions/livy-20231025/livy/livy.sh

**Comment by cjac** [comment]
Can  you confirm that this fixes your issue, @saimaung ?

**Comment by FrankieChoi** [comment]
> Can you confirm that this fixes your issue, @saimaung ?

Thanks for the quick fix. It works as a charm

**Comment by saimaung** [comment]
> Can you confirm that this fixes your issue, @saimaung ?

@cjac the issue is good to close, thanks as @FrankieChoi help verified the fix.
