### ISSUE TITLE
Flink init action configuration is incorrect on some machine types

### ISSUE THREAD

**Issue by karth295** [GoogleCloudDataproc/initialization-actions#182]
I noticed this todo: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/flink/flink.sh#L66.

While most machine types have two executors per machine, 1-core and 8+-core machines do not. I have an example in https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/pull/181/files on how to calculate this correctly based on YARN vcores.

**Comment by bsidhom** [comment]
Is this done in `CORES_PER_NODEMANAGER`? How reliable is that approach?

**Comment by karth295** [comment]
I've tested on 1.2 and 1.0 and it seems to work. The alternative is to query the RM REST API, but idk how to reliably do this in HA mode.

And it's more than just `CORES_PER_NODEMANAGER`, it's this whole sequence here:

```
ROLE=$(/usr/share/google/get_metadata_value attributes/dataproc-role)
WORKER_COUNT=$(/usr/share/google/get_metadata_value attributes/dataproc-worker-count)

if [[ "${ROLE}" == "Master" ]]; then
  NUM_NODEMANAGERS_TARGET="${WORKER_COUNT}"
  if (( "${WORKER_COUNT}" == 0 )); then
    # Single node clusters have one node manager
    NUM_NODEMANAGERS_TARGET=1
  fi
  # Wait for 5 minutes for Node Managers to register and run.
  # Break early if the expected number of node managers have registered.
  for (( i=0; i < 5*60; i++ )); do
    CURRENTLY_RUNNING_NODEMANAGERS=$(yarn node -list | grep RUNNING | wc -l)
    if (( CURRENTLY_RUNNING_NODEMANAGERS == NUM_NODEMANAGERS_TARGET )); then
      break
    fi
    sleep 1
  done
  if (( CURRENTLY_RUNNING_NODEMANAGERS == 0 )); then
    echo "No node managers running. Cluster creation likely failed"
    exit 1
  fi

  # Assumes customers have not touched vcores per node
  CORES_PER_NODEMANAGER=$(yarn node -list | tail -n 1 | cut -f 1 -d ' ' | xargs yarn node -status | perl -ne '/CPU-Capacity : (\d+) vcores/ && print "$1\n";')
fi
```

**Comment by medb** [comment]
Closing as obsolete because Flink is supported as a Dataproc component now: https://cloud.google.com/dataproc/docs/concepts/components/flink
