### ISSUE TITLE
Document how to use Livy init action

### ISSUE THREAD

**Issue by karth295** [GoogleCloudDataproc/initialization-actions#235]
We now have a Livy init action, but don't really have instructions on how to use it. Things that come to mind are:

- How would I set up Hue to use Livy? How about Jupyter or Zeppelin? Or even my webserver? Would I want to do any of those things?
- Networking. Default GCE firewall rules block Livy's port (which is what you want because Dataproc relies on perimeter security). The easiest thing to do is to make Livy requests from another GCE VM on the same VPC network.

Part of this issue will also making some of these use cases "easy". Modifying the Hue init action to recognize Livy is installed is an easy win, because that's the only way to run Spark in Hue.

If any community members have opinions on what we should document or what we use cases we should make easy, please chime in!

**Comment by medb** [comment]
Livy is not actively supported anymore.
