### ISSUE TITLE
Spark-Packages in Jupyter Init

### ISSUE THREAD

**Issue by jameswinegar** [GoogleCloudDataproc/initialization-actions#252]
What would be the preferred way to add the ability to pass in spark-packages metadata for Jupyter kernels? This should work similarly to DataLab implementation.

https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/jupyter/kernels/generate-pyspark.sh

Currently has the following
```
if (( "${SPARK_MAJOR_VERSION}" >= 2 )); then
  PACKAGES_ARG=''
else
  PACKAGES_ARG='--packages com.databricks:spark-csv_2.10:1.3.0'
fi
```
It will need handling if no package metadata is passed since we can't just pass the `--packages` argument around if we don't reference any packages for Spark 2.x

**Comment by karth295** [comment]
Most `spark-submit` flags actually just boil down to config parameters: https://spark.apache.org/docs/latest/configuration.html#runtime-environment.

In this case, the relevant config is just `spark.jars.packages=<comma-separated-list-of-packages>`. There's also a flag for specifying repositories other than Maven central.

So I would usually do something like:

```
gcloud dataproc clusters create ... --properties "spark:spark.jars.packages=com.databricks:spark-csv_2.10:1.3.0"
```

Reference on specifying properties when creating Dataproc clusters: https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/cluster-properties.

But I can see how that's hard to find. Feel free to open a PR adding a metadata key like `SPARK_JAVA_PACKAGES`. We generally use GCE VM metadata keys to pass arguments to init actions. Jupyter already has a few (JUPYTER_CONDA_PACKAGES, etc) for reference. If you do open a PR, please modify both `jupyter` and `jupyter2`.

**Comment by jameswinegar** [comment]
I solved my current issue by adjusting the API call I'm doing when creating the cluster.

I'd like to come back and extend this, but since there's a valid solution outside of the initialization actions, i'm not sure what purpose that solves.
