### ISSUE TITLE
Flink initializing script uses only first master name when high availability cluster is created

### ISSUE THREAD

**Issue by igroeg** [GoogleCloudDataproc/initialization-actions#272]
The problem is with :
`/usr/share/google/get_metadata_value attributes/dataproc-master` 
It will always return the first master e.g - cluster-name-m-0 even when the script is currently running on the second master. The other masters are available only through the   `attributes/dataproc-master-additional ` option, but it returns all other masters and not the current one. Of course it could be used `hostname` as a variable, but this is not a clean way, cause if you try to setup something in the slaves, hostname will be resolved as the slave's name and will not point to the master.

**Comment by karth295** [comment]
Thanks for the issue! We've been slowly fixing various init actions on HA clusters.

So far, we have used `${HOSTNAME} == ${dataproc_master}` when we need something to run only one one node (e.g. running a notebook server), and have used `${role} == 'Master'` when we need to run something on all masters (such as installing a library). Not all daemons can run on multiple servers simultaneously, so always using `-m-0` is a convenient choice.

Here is an example: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/jupyter2/jupyter2.sh#L109.

Here is a more complex example with different pieces to run on masters vs workers: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/cloud-sql-proxy/cloud-sql-proxy.sh#L216. I'll admit it's a bit confusing.

I see two options for fixing this issue:

1) Run Flink in HA mode (probably should not run Flink-on-YARN then): https://cwiki.apache.org/confluence/display/FLINK/JobManager+High+Availability
2) Only run this script on `-m-0` using `$HOSTNAME`. And nit: the `configure_flink` function should be split into `configure_flink` and `run_flink`. 

Option 2 is quick and easy, but I'm not convinced it makes sense to run an HA cluster if you're going to do that. I'm leaning toward option 1, but I would accept a PR for option 2 as well.

CC @bsidhom (the resident Flink expert)

**Comment by bsidhom** [comment]
I have not attempted to run a Flink JobManager in HA mode, but note that we made the explicit decision to only run a detached yarn session on the first master in #122.

@karth295 I'm not sure why you suggest what we would not run Flink-on-YARN. Any beyond-YARN Flink deployments should probably not be using Dataproc in the first place. Luckily, it sounds like it should be pretty easy to set up HA on YARN. The bad news is that it requires a change to `yarn-site.xml` https://ci.apache.org/projects/flink/flink-docs-release-1.5/ops/jobmanager_high_availability.html#yarn-cluster-high-availability.

**Comment by szewi** [comment]
@bsidhom @karth295 I just noticed that Flink initialization action is failing on HA. All three masters are submitting Flink Yarn session with the same name, however, only one is considered as deployed. I guess there should be just one detached session but deployed in HA mode. I updated the flink init action to modify flink config when running on HA clusters. Could you take a look?
