### ISSUE TITLE
Jupyter creating or open notebooks causes 500 Internal Server Error

### ISSUE THREAD

**Issue by justinnaldzin** [GoogleCloudDataproc/initialization-actions#480]
The initialization action for installing Jupyter and connecting to the web interface is successful.  However opening an existing notebook or creating a new notebook results in a `500 : Internal Server Error`.
![Screen Shot 2019-03-13 at 10 07 59 AM](https://user-images.githubusercontent.com/12646414/54286233-cf224600-4579-11e9-8041-b8d38a481bce.png)

**Comment by MaxAVF** [comment]
I'm having the same problem. Any clue about what seems to be the problem?

**Comment by medb** [comment]
What Dataproc image version do you use? May you share cluster creation command?

**Comment by MaxAVF** [comment]
@medb 
´´´
gcloud dataproc clusters create [clustername] --bucket [bucket-name] --region southamerica-east1 --subnet default --zone southamerica-east1-a --single-node --master-machine-type n1-standard-16 --master-boot-disk-size 500 --image-version 1.3-deb9 --project gc-la-voz --initialization-actions 'gs://dataproc-initialization-actions/jupyter/jupyter.sh'

´´´

**Comment by medb** [comment]
@MaxAVF for Dataproc 1.3 and aboce you should use [Jupyter Notebook](https://cloud.google.com/dataproc/docs/concepts/components/jupyter) [Component](https://cloud.google.com/dataproc/docs/concepts/components/overview) which is has official support in contrast to init actions:
```
gcloud dataproc clusters create <CLUSTER_NAME> \
    --optional-components=ANACONDA,JUPYTER \
    --image-version=1.3 \
```

**Comment by MaxAVF** [comment]
I tried with the jupyter notebook Component, but it doesnt show the notebooks that i have on the bucket... I dont know why. Anyways the init action was working fine until yesterday.

**Comment by ujjwal** [comment]
Yeah. Seeing the same issue since yesterday. The init script installs some conda packages for us. And sets up the bucket locations.

**Comment by MaxAVF** [comment]
Tried the init action with image-version=1.2, the same issue still persist.

**Comment by justinnaldzin** [comment]
Dataproc version is:  1.3-deb9

Using the following gcloud command: `gcloud dataproc clusters create ${CLUSTER_NAME} --bucket ${BUCKET_NAME} --zone us-east1-d --master-machine-type n1-standard-4 --master-boot-disk-size 1TB --num-workers 3 --worker-machine-type n1-standard-4 --worker-boot-disk-size 1TB --image-version 1.3-deb9 --scopes 'https://www.googleapis.com/auth/cloud-platform' --project ${PROJECT_ID} --initialization-actions gs://dataproc-initialization-actions/connectors/connectors.sh,gs://dataproc-initialization-actions/conda/bootstrap-conda.sh,gs://dataproc-initialization-actions/conda/install-conda-env.sh,gs://dataproc-initialization-actions/jupyter/jupyter.sh --metadata 'gcs-connector-version=1.9.13' --metadata 'bigquery-connector-version=0.13.13'`

**Comment by justinnaldzin** [comment]
Using Optional components includes a Python2 kernel but there is **no Python 3 kernel**.  So that is why I am using the init action.

**Comment by medb** [comment]
For Python 3 you need to use Dataproc 1.4 (`--image-version=preview`) with Jupyter Component.

**Comment by michelle-unity** [comment]
I've switched to Dataproc 1.4 but still seeing the same `500 : Internal Server Error`

gcloud command below: 
`  gcloud beta dataproc clusters create ${CLUSTER_NAME}\
   --project ${PROJECT_NAME} \
   --bucket=${BUCKET_NAME} \
   --service-account="test-pipeline-prd@test-prd.iam.gserviceaccount.com" \
   --tags="adhoc,allow-private-ssh-prd,spark-dataproc,allow-internal-consul-ports" \
   --region us-central1 \
   --zone us-central1-f \
   --subnet=projects/test-ie-network/regions/us-central1/subnetworks/test-prd-gusc1-1 \
   --master-machine-type n1-highmem-8 \
   --master-boot-disk-size 1000 \
   --num-workers 2 \
   --worker-machine-type n1-highmem-32 \
   --worker-boot-disk-type pd-ssd \
   --worker-boot-disk-size 200 \
   --image-version=preview \
   --properties "core:fs.gs.metadata.cache.enable=false,capacity-scheduler:yarn.scheduler.capacity.resource-calculator=org.apache.hadoop.yarn.util.resource.DominantResourceCalculator" \
   --no-address \
   --initialization-actions "gs://dataproc-initialization-actions/jupyter/jupyter.sh" \
   --metadata "JUPYTER_PORT=8300,JUPYTER_CONDA_PACKAGES=numpy:tensorflow:sparkmagic:ipython-sql:google-cloud-storage,JUPYTER_CONDA_CHANNELS=conda-forge:defaults"
`

**Comment by sukhinin541** [comment]
I'm using --image-version=1.2 and also got the same error this morning. When I checked /var/log/jupyter.log on the master node, I saw the following error:

AttributeError: module 'tornado.web' has no attribute 'asynchronous'

I then followed a recommendation to downgrade to conda install tornado=5.1.1, and restarted Jupyter /usr/local/bin/launch_jupyter.sh

This fixed the issue in my currently running cluster.

Unfortunately, the original error caused my notebook to be overwritten in the bucket with
{
 "cells": [],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 2
}

Good that I created a backup beforehand, and now have bucket versioning turned on to prevent loosing my work in the future.

**Comment by medb** [comment]
@michelle-unity with Dataproc 1.4 you need to use components instead of init actions:
```
--optional-components=ANACONDA,JUPYTER \
```

**Comment by MaxAVF** [comment]
@medb So, basically this initialization action is not working anymore and we shouldn´t use it anymore? And instead use the optional component from now on?

**Comment by medb** [comment]
We will fix this init action (no ETA though), but eventually we will deprecate all init actions that have corresponding optional components. Meanwhile, the rule of thumb is "you should prefer optional component over init action, if it's available".

**Comment by sukhinin541** [comment]
When using optional components, according to [this document](https://cloud.google.com/dataproc/docs/tutorials/python-configuration), 

> You can install Conda and PIP packages with the conda initialization action and the pip install initialization action.

However, `.../python/conda-install.sh` script doesn't allow to add conda channels like in a similar `jupyter.sh` script (via `JUPYTER_CONDA_CHANNELS`).

Can this functionality be added to `conda-install.sh` or is there any other way to install conda packages from multiple channels when using optional components?
