### ISSUE TITLE
Knox init action contribution

### ISSUE THREAD

**Issue by yunus** [GoogleCloudDataproc/initialization-actions#603]
Hi,

I am a SCE (googler). I have created a knox init action. It installs and configures the bigtop provided apache knox. A pull request will follow where in readme i explain all the features.

The background of this issue is in https://docs.google.com/document/d/1sRVWHepHCAPrKHVfOKt6GZqnbASg1z1L0187IpeCPqo/edit

**Comment by medb** [comment]
Knox init actions was merged in #719
