### ISSUE TITLE
Presto component configuration

### ISSUE THREAD

**Issue by orenovadia** [GoogleCloudDataproc/initialization-actions#605]
I need to add the following to the presto (optional component) configuration:
`hive.parquet.use-column-names=true` in `/opt/presto-server/etc/catalog/hive.properties`

This parameter is just an example, but today, there is no way to modify the presto configuration at deploy time, (e.g.: by parameters given to `gcloud dataproc clusters create ...`).

Thanks

**Comment by karth295** [comment]
As a temporary workaround, you can run an initialization action to modify that file.

But I agree with this feature request long term.

**Comment by medb** [comment]
Dataproc [Presto component](https://cloud.google.com/dataproc/docs/concepts/components/presto) supports configuration via [cluster properties](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/cluster-properties) with `presto:` prefix.
