### ISSUE TITLE
Upgrade Dataproc initialization to latest TF version and TonY version

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudDataproc/initialization-actions#616]
Upgrade to TF 1.15
Upgrade to latest Tony Client

**Comment by gogasca** [comment]
@bradmiro

**Comment by medb** [comment]
@bradmiro may you take a look into this?

**Comment by bradmiro** [comment]
Sure, I'll do this this week :)

**Comment by bradmiro** [comment]
Fix PR: [#724 ](https://github.com/GoogleCloudDataproc/initialization-actions/pull/724)

**Comment by medb** [comment]
Fixed in #865
