### ISSUE TITLE
Livy initialization action fails when used in conjunction with Kerberos

### ISSUE THREAD

**Issue by sblcook** [GoogleCloudDataproc/initialization-actions#622]
The Livy initialization action fails when it is used in conjunction with Kerberos because there are extra configurations that need to be added to the `livy.conf` file when Kerberos is the authentication method for Livy. 

A simple change could be to modify the script to create a new Kerberos principal for Livy and to update the configuration file. I currently have a PR which does this and just requires so more testing.

**Comment by medb** [comment]
@sblcook May you share your PR?

**Comment by medb** [comment]
Livy is not actively supported anymore.
