### ISSUE TITLE
JupyterLab component: "Server Connection Error. Invalid Response: 500"

### ISSUE THREAD

**Issue by irlesv** [GoogleCloudDataproc/initialization-actions#714]
Hello, 

I'm creating a cluster with Jupyter install on it as usual but today it seems it cannot connect to my bucket in Google Storage. Instead of having a list of all my notebooks I am having the following message: 

![Capture](https://user-images.githubusercontent.com/54353897/72721793-c1175b80-3b74-11ea-903a-9fe38ed6376d.JPG)

I am creating the cluster in the following way:
```bash
gcloud beta dataproc clusters create cluster-test20 ^
    --enable-component-gateway ^
    --service-account=[my service account] ^
    --region=europe-west1 ^
    --optional-components=ANACONDA,JUPYTER ^
    --image-version=1.4 ^
    --bucket [my bucket] ^
    --project [my gcp project] ^
    --metadata PIP_PACKAGES=pandas-gbq ^
    --initialization-actions gs://dataproc-initialization-actions/python/pip-install.sh ^
    --properties "spark:spark.jars=gs://spark-lib/bigquery/spark-bigquery-latest.jar"
```

I can still create Jupyter Notebooks and save them in my bucket but I don't find a way to see and load the existing ones.
Just to mention that this has been working fine until last Friday. Any idea why this might not be working today? Thanks

**Comment by medb** [comment]
Most probably this is intermittent issues with Cloud Storage, can you retry it one more time?
