### ISSUE TITLE
Example shows 2 slashes instead of 3

### ISSUE THREAD

**Issue by premCsup** [GoogleCloudDataproc/initialization-actions#722]
The paragraph here [1, 2] shows 2 slashes instead of 3, which has made at least one user to be blocked in their development and production.

Please fix the guide, or provide more examples if there are alternative uses for the operation.

[1] https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/hbase#using-different-storage-for-hbase-data
[2] REGION=<region>
CLUSTER_NAME=<cluster_name>
gcloud dataproc clusters create ${CLUSTER_NAME} \
    --region ${REGION} \
    --initialization-actions gs://goog-dataproc-initialization-actions-${REGION}/hbase/hbase.sh \
    --metadata 'hbase-root-dir=gs://<BUCKET_NAME>/' \
    --metadata 'hbase-wak-dir=hdfs://path/to/wal' \
    --num-masters 3 --num-workers 2

**Comment by medb** [comment]
HDFS path with 2 slashed is also valid - it means that host/authority should be explicitly specified, 3 slashes means that default FS is used. The same applies to all [other URLs](https://superuser.com/questions/352133/why-do-file-urls-start-with-3-slashes).
