### ISSUE TITLE
Multiple instances in additional-cloud-sql-instances property

### ISSUE THREAD

**Issue by mrsirsh** [GoogleCloudDataproc/initialization-actions#747]
Documentation for cloudproxy suggests that `--instances` and `--instances_metadata` both allow a comma separated list of instances. Locally if i run cloudproxy with a list of instances it opens connections to both and starts listening but using the cloud proxy init task, which takes
```
 --metadata "additional-cloud-sql-instances= ..."
```
and passes it on to ` --instances_metadata` there is a parse error
```
INVALID_ARGUMENT: Metadata key 'PROJECT:REGION:DB' must match pattern [a-zA-Z0-9-_]{1,128}
```
I believe i also tried passing the metadata as two separate arguments in which case I believe only the latter takes effect.

What is the correct way to deal with an arbitrary number of instances here?

**Comment by chingtzunglin** [comment]
I ran into the same issue. Appreciate any advice.

Here is what the doc said. It may also missing a ':' between protocol and local port.

--metadata "additional-cloud-sql-instances=<PROJECT_ID>:<REGION>:<ANOTHER_INSTANCE_NAME>=tcp<PORT_#>[,...]"

**Comment by medb** [comment]
May you check logs for init action failure and attach full error here?

**Comment by chingtzunglin** [comment]
gcloud dataproc cluster create returns error immediately. I don't think it gets to validate cloudsql instances yet.

Here is my additional-cloud-sql-instances setting:
--metadata "additional-cloud-sql-instances=myproject:us-east1:sql1=TCP:5432:myproject:us-east1:sql2=TCP:5433" 

ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Metadata key 'myproject:us-east1:sql2' must match pattern [a-zA-Z0-9-_]{1,128}
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: "[ORIGINAL ERROR] generic::invalid_argument: com.google.cloud.hadoop.services.common.error.DataprocException:\
    \ Metadata key 'myproject:us-east1:sql2' must match pattern [a-zA-Z0-9-_]{1,128}\
    \ (INVALID_ARGUMENT) [google.rpc.error_details_ext] { message: \"Metadata key\
    \ \\'myproject:us-east1:sql2\\' must match pattern [a-zA-Z0-9-_]{1,128}\" }"

The problem may be related to metadata parsing. It expects a key=value[,...] and for this particular case, the value itself has both '=' and ',' when multiple instances are specified.
Parser may break and misidentified the second sql instance as the key for metadata.

[1] https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/metadata

**Comment by medb** [comment]
What OS and `gcloud` version do you use?

I just tried to create cluster with provided metadata and it works:

```bash
gcloud dataproc clusters metadata-test \
  --metadata "additional-cloud-sql-instances=myproject:us-east1:sql1=TCP:5432:myproject:us-east1:sql2=TCP:5433"
```

**Comment by chingtzunglin** [comment]
I am on Debian Linux.
gcloud version
Google Cloud SDK 249.0.0
alpha 2019.05.17
beta 2019.05.17
bq 2.0.43
core 2019.05.31
gsutil 4.38
kubectl 2019.05.31

The spec you set to additional-cloud-sql-instances may be wrong, I belive it needs ',' to separate between two instead of ':'

**Comment by medb** [comment]
There was typo in metadata, I have reproduced this error by replacing `:` with `,`:
```bash
$ gcloud dataproc clusters create metadata-test \
  --metadata "additional-cloud-sql-instances=myproject:us-east1:sql1=TCP:5432,myproject:us-east1:sql2=TCP:5433" 

ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Metadata key 'myproject:us-east1:sql2' must match pattern [a-zA-Z0-9-_]{1,128}
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: "[ORIGINAL ERROR] generic::invalid_argument: com.google.cloud.hadoop.services.common.error.DataprocException:\
    \ Metadata key 'myproject:us-east1:sql2' must match pattern [a-zA-Z0-9-_]{1,128}\
    \ (INVALID_ARGUMENT) [google.rpc.error_details_ext] { message: \"Metadata key\
    \ \\'myproject:us-east1:sql2\\' must match pattern [a-zA-Z0-9-_]{1,128}\" }"
```

To fix this issue you need to override metadata properties delimiter to be other character than comma (`,`), here is an example how to do this for asterisk (`*`):
```bash
gcloud dataproc clusters create idv-sql-02 \
  --metadata "^*^additional-cloud-sql-instances=myproject:us-east1:sql1=TCP:5432,myproject:us-east1:sql2=TCP:5433" 
```

This escape syntax is [documented](https://cloud.google.com/sdk/gcloud/reference/topic/escaping) in `gcloud`.

**Comment by chingtzunglin** [comment]
thanks! indeed changing the delimiter resolved the issue.

**Comment by mrsirsh** [comment]
Amazing! thanks for pointing this out - i can only imagine it would have taken me some time to see it was an escape sequence issue!
