### ISSUE TITLE
Oozie application path pointing to a gs schema throws "gs URI scheme not supported"

### ISSUE THREAD

**Issue by brubom** [GoogleCloudDataproc/initialization-actions#748]
When using a oozie properties files pointing to a gs bucket, we're receiving a "gs URI scheme not supported" exception. 

`oozie.coord.application.path=gs://my_workflow/workflows/daily`

There is a [workaround for this](https://stackoverflow.com/questions/61233551/how-to-use-gcp-bucket-as-workflow-file-source-for-oozie-in-dataproc/61237392#61237392), but it would be awesome to have it out of the box.

**Comment by Gaurangi94** [comment]
Resolved in https://github.com/GoogleCloudDataproc/initialization-actions/pull/798
