### ISSUE TITLE
GPU initialization action does not create GPU metrics

### ISSUE THREAD

**Issue by tfayyaz** [GoogleCloudDataproc/initialization-actions#756]
While testing I found that the GPU initialization action does not actually create the stackdriver monitoring metrics.

I had to create the metrics externally by running the following code in cloud shell taken from [here](https://github.com/GoogleCloudPlatform/ml-on-gcp/tree/master/dlvm/gcp-gpu-utilization-metrics) 

```
git clone https://github.com/GoogleCloudPlatform/ml-on-gcp.git
cd ml-on-gcp/dlvm/gcp-gpu-utilization-metrics 
pip install -r ./requirements.txt
python create_gpu_metrics.py 
```

it's not clear if the user should be creating the metrics or this should be done by the init action?

**Comment by medb** [comment]
To create GPU metrics in init action you need to set `install-gpu-agent=true` metadata value when creating a cluster: https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/gpu#supported-metadata-parameters
