### ISSUE TITLE
Jupyter optional component source code? 

### ISSUE THREAD

**Issue by DBCerigo** [GoogleCloudDataproc/initialization-actions#766]
I'm trying to create a Dataproc cluster that uses the Jupyter optional component as well as runs a custom initialization action which installs some more python packages. I'm getting some errors when trying to create or open notebooks through the jupyter server - I think due to version clashes between some jupyter-related packages that get installed as part of my custom initialization actions.

My questions are: 
- could you point me to the source code for the Jupyter component? (I can find it for the old initialisation action version)
- how would one go about restarting the Jupyter server on a running cluster? The output from running `jupyter notebook list` on the server is `Currently running servers:` only.

Thanks :) 

The exact error for ref:
```
jsonschema.exceptions.ValidationError: 2 is less than the minimum of 4
    
    Failed validating 'minimum' in schema['properties']['nbformat_minor']:
        {'description': 'Notebook format (minor number). Incremented for '
                        'backward compatible changes to the notebook format.',
         'minimum': 4,
         'type': 'integer'}
    
    On instance['nbformat_minor']:
        2
```

**Comment by medb** [comment]
Optional components code is not open sourced in the same way as init actions code.

Why do you need Jupyter component code? You should be able to inspect Jupyter and/or Anaconda environment after cluster creation.

If you need to install conda/pip Python packages during cluster creation then you should use [python](https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/python) initialization action.

**Comment by DBCerigo** [comment]
> Optional components code is not open sourced in the same way as init actions code.

This answers it, thanks :)
