### ISSUE TITLE
Horovod initialization script

### ISSUE THREAD

**Issue by roarjn** [GoogleCloudDataproc/initialization-actions#775]
Hi,
I am trying to install Horovod on Dataproc nodes. Here are the steps I am following in my initialization actions script. However, I am not able to get openmpi or horovod installed on the worker nodes. It seems like the error is with the openmpi install steps. Manually doing these steps by ssh into worker nodes works.

To install openmpi (following instructions from [here](https://www.open-mpi.org/faq/?category=building#easy-build))
```
wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.4.tar.gz
 tar -xzf openmpi-4.0.4.tar.gz
 cd /usr/lib/openmpi-4.0.4
 sudo ./configure --prefix=/usr/local
 sudo make all install
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```
tp install Horovod (following instructions from [here](https://github.com/horovod/horovod#install))
```
HOROVOD_GPU_OPERATIONS=NCCL pip install --user horovod
```

Could any instructions/pointers be provided to install Horovod on Dataproc nodes (with GPU support)?
Appreciate any help!

Thanks,

**Comment by medb** [comment]
Can you install openmpi from Debian repo: `apt install openmpi-bin`?

**Comment by roarjn** [comment]
Thanks.. I can install by `apt install openmpi-bin`. Do I need to specify `LD_LIBRARY_PATH` for horovod to know mpi path?

**Comment by bradmiro** [comment]
Try running `ldconfig` after `make`. I believe I faced a similar issue and recall this working.

**Comment by medb** [comment]
Yes, seems like you need to set `LD_LIBRARY_PATH` for Horovod GPU support: https://horovod.readthedocs.io/en/stable/gpus_include.html
