### ISSUE TITLE
RAPIDS xgboost jars for Spark 2.4/Scala 2.12

### ISSUE THREAD

**Issue by bradmiro** [GoogleCloudDataproc/initialization-actions#784]
We should ensure the xgboost jars in the rapids init action support Spark 2.4 / Scala 2.12 with Dataproc 1.5. While the tests pass, there are no guarantees that all functionality is supported.

**Comment by bradmiro** [comment]
@mengdong per our conversation. Please LMK as you get updates here :)

**Comment by mengdong** [comment]
Yes, I had let engineers know and they are going to release a jar soon.

**Comment by bradmiro** [comment]
Closing this. We can come back to this if the feature ends up requested down the road.
