### ISSUE TITLE
gcloud dataproc cluster create with cloud-sql-proxy dataproc-initialization-actions fails

### ISSUE THREAD

**Issue by attoomai** [GoogleCloudDataproc/initialization-actions#801]
Steps to reproduce:

1. Create GCP project.
2. Spin up a Cloud SQL instance (a MySQL instance)
3. Create a Dataproc cluster with initialization action to install Cloud SQL Proxy

Command used:

```bash
bucket=<BUCKET>
cluster_name=<CLUSTER>
instance_name=<INSTANCE>

gcloud dataproc clusters create $cluster_name \
  --region=<REGION - same as Cloud SQL instance> \
  --zone=<ZONE - same as Cloud SQL instance> \
  --scopes=default,sql-admin \
  --initialization-actions=gs://<BUCKET>/dataproc-initialization-actions/cloud-sql-proxy/cloud-sql-proxy.sh \
  --properties=hive:hive.metastore.warehouse.dir=$bucket/hive-warehouse \
  --metadata=enable-cloud-sql-hive-metastore=false \
  --metadata=additional-cloud-sql-instances=< INSTANCE_NAME>\
  --master-machine-type n1-standard-1 \
  --master-boot-disk-size 20 \
  --num-workers 2 \
  --worker-machine-type n1-standard-2 \
  --worker-boot-disk-size 20 \
  --image-version 1.2
```

Failure:

```
Failed to enable unit: File cloud-sql-proxy.service: Invalid argument
```

Attached is the [log file](https://github.com/GoogleCloudDataproc/initialization-actions/files/5140466/log.txt).

Do have two questions,
1. Help related. to the error.
2. I might be using the wrong `cloud-sql-proxy.sh`. file. Would appreciate if you please share the right file.

**Comment by animeshnandanwar** [comment]
Did you set a password when creating the instance? If so, you need to pass in an admin password in order for the script to setup instance.
Also, how did you pass in cloud-sql-instance name ?
Usually it is of format "google.com:<PROJECT>:<REGION>:< INSTANCE_NAME>"

**Comment by animeshnandanwar** [comment]
Closing issue as did not get asked info from submitter.
