### ISSUE TITLE
Initialization action for prometheus fails, because centra.maven.org no longer exists

### ISSUE THREAD

**Issue by mic47** [GoogleCloudDataproc/initialization-actions#804]
Initialization action for prometheus fails, because it tried to download dependencies from domain that does not exists (central.maven.org). repo1.maven.org should work, also, it needs https, since 9m ago they started requiring https.

This is from error log:
```
+ wget -nv --timeout=30 --tries=5 --retry-connrefused http://central.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.11.0/jmx_prometheus_javaagent-0.11.0.jar -P /usr/lib/kafka/libs
wget: unable to resolve host address ‘central.maven.org’
```

https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/prometheus/prometheus.sh#L31

**Comment by Gaurangi94** [comment]
Thanks for bringing this to our attention! This has now been fixed.
https://github.com/GoogleCloudDataproc/initialization-actions/pull/807
