### ISSUE TITLE
Updating default RAPIDS version for Dataproc 1.5

### ISSUE THREAD

**Issue by bradmiro** [GoogleCloudDataproc/initialization-actions#832]
Hey @mengdong ,

It looks like the default cudf version on Dataproc 1.5 with Spark 2.x is still 0.9.2. As there does not appear to be any prebuilt jars for cudf 0.9.2 and cuda 10.2 (current default cuda version for the init action), is this safe to update?

**Comment by mengdong** [comment]
Hi Brad, I think

```
if [[ "${SPARK_VERSION_ENV}" == "3"* ]]; then
  readonly DEFAULT_CUDF_VERSION="0.15"
  readonly DEFAULT_SPARK_RAPIDS_VERSION="0.2.0"
  readonly SPARK_VERSION="${SPARK_VERSION_ENV}"
else
  readonly DEFAULT_CUDF_VERSION="0.9.2"
  readonly DEFAULT_SPARK_RAPIDS_VERSION="Beta5"
  readonly SPARK_VERSION="2.x"
fi
```

We default cudf to 0.9.2 for spark 2.x, it is safe to upgrade dataproc image as long as it is still using spark 2.x.

**Comment by bradmiro** [comment]
Ok awesome, so all of these are compiled for Spark 2.x? https://repo1.maven.org/maven2/ai/rapids/cudf/0.16/

**Comment by mengdong** [comment]
For spark 2.x we need to stick with cudf 0.9.2 as what we currently have for spark + cudf.

**Comment by bradmiro** [comment]
Got it. Is cuda 10.2 supported with RAPIDS 0.9.2?

**Comment by mengdong** [comment]
Good catch, yeah seems like only cuda 10.1 for 0.9.2
