### ISSUE TITLE
Update TONY for Dataproc 1.5 (documentation) 

### ISSUE THREAD

**Issue by cpcgoogle** [GoogleCloudDataproc/initialization-actions#834]
The TonY installation now fails on the Dataproc default version of 1.3 due to a Python conflict. That's okay if we just want to deprecate the 1.3, but we should update the documentation/example showing that the cluster should be built with 1.5 and say that 1.3 is no longer supported. 

The job submission example in the blog post also needs updated to the TonY cli version that is now installed (TONY_JARFILE=tony-cli-0.3.23-all.jar) and the python virtual env of 3.7 instead of 3.5.  

I don't think we need to update the original blog since the TonY one has all the same info but it would be handy to drop the job submission examples on this Git page with the updates. You could make the updates variables so users understand they may have to change them over time.

**Comment by bradmiro** [comment]
Thanks @cpcgoogle, working on updating these this week.
