### ISSUE TITLE
Error installing rapids: 404 on cudf download URL

### ISSUE THREAD

**Issue by chensun** [GoogleCloudDataproc/initialization-actions#862]
This specific handling added by https://github.com/GoogleCloudDataproc/initialization-actions/pull/812 only works for 11-0, and is broken after the version downgrade https://github.com/GoogleCloudDataproc/initialization-actions/pull/819:

https://github.com/GoogleCloudDataproc/initialization-actions/blob/251d7ab2ccf8a325b1a576e6bedb6fa75e6b8cee/rapids/rapids.sh#L91-L92

I was using gs://goog-dataproc-initialization-actions-us-central1/rapids/rapids.sh, and hit the error:
```
+ wget -nv --timeout=30 --tries=5 --retry-connrefused https://repo1.maven.org/maven2/ai/rapids/cudf/0.9.2/cudf-0.9.2-cuda10-2.jar -P /usr/lib/spark/jars/
https://repo1.maven.org/maven2/ai/rapids/cudf/0.9.2/cudf-0.9.2-cuda10-2.jar:
2021-02-03 11:59:13 ERROR 404: Not Found.
```

**Comment by medb** [comment]
This is because cuDF 0.9.2 does not support CUDA 10.2: https://repo1.maven.org/maven2/ai/rapids/cudf/0.9.2/

Please use another version of cuDF and/or CUDA that are compatible with each other.

**Comment by medb** [comment]
cuDF 0.14 should work with CUDA 10.2: https://repo1.maven.org/maven2/ai/rapids/cudf/0.14/

**Comment by chensun** [comment]
Hi @medb, the issue is about `gs://goog-dataproc-initialization-actions-us-central1/rapids/rapids.sh` doesn't work out of the box.
cuDF 0.9.2 and CUDA 10.2 are currently default values specified in that script, if they're not compatible, the script still needs a fix.

**Comment by medb** [comment]
I think that better fix is to fix use a proper CUDA version: https://github.com/GoogleCloudDataproc/initialization-actions/pull/864
