### ISSUE TITLE
Update Livy to version 0.8.0

### ISSUE THREAD

**Issue by wsmolak** [GoogleCloudDataproc/initialization-actions#870]
https://github.com/GoogleCloudDataproc/initialization-actions/blob/27e99c923cdc6fc1bd4e0ff22722d93e74605a57/livy/livy.sh#L17

It's not possible to use Livy with Dataproc 1.5+ due to Scala version change. Livy supports Scala 2.12 from 0.8.0 version.

**Comment by medb** [comment]
0.8.0 is not a released Livy version, that's why we can not update to it: https://search.maven.org/search?q=g:org.apache.livy
