### ISSUE TITLE
Livy with Python 3.X

### ISSUE THREAD

**Issue by wsmolak** [GoogleCloudDataproc/initialization-actions#871]
By default Livy uses Python 2.7. Due to deprecation of that branch only Python3 should be used for DataProc 1.4+

Solution:

Minoconda:
```
export PYSPARK_PYTHON=/opt/conda/miniconda3/bin/python3
export PYSPARK_DRIVER_PYTHON=/opt/conda/miniconda3/bin/python3
```

Anaconda:
```
export PYSPARK_PYTHON=/opt/conda/anaconda/bin/python3
export PYSPARK_DRIVER_PYTHON=/opt/conda/anaconda/bin/python3
```

Paths from: https://cloud.google.com/dataproc/docs/tutorials/python-configuration#image_version_14

**Comment by medb** [comment]
May send a PR for Livy init action with this fix?
