### ISSUE TITLE
[Pull request] check if the chars passed by javax.jdo.option.ConnectionPassword are valid xml chars 

### ISSUE THREAD

**Issue by CatCassie** [GoogleCloudDataproc/initialization-actions#892]
[cloud-sql-proxy.sh](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/cloud-sql-proxy/cloud-sql-proxy.sh) didn't check if the chars passed to `javax.jdo.option.ConnectionPassword` contains invalid xml chars such as `&` to passed to `hive-site.xml` file on the VM.

Where to add the check?
We should check [DB_HIVE_PASSWORD](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/cloud-sql-proxy/cloud-sql-proxy.sh#L81) doesn't contain any invalid xml chars before applying.

**Comment by CatCassie** [comment]
Can you please review the issue and I am happy to submit a pull request for it :)

**Comment by CatCassie** [comment]
Thanks for your swift response!

**Comment by medb** [comment]
Expected behavior that init action will fast-fail if password has these characters, or will escape then so it could be passed in Hive XML config?

**Comment by CatCassie** [comment]
Good question! I think we should fast fail and provide user an error message says their password contains a invalid xml character. What do you think?

**Comment by medb** [comment]
For posterity the same issue was reported in https://github.com/GoogleCloudDataproc/initialization-actions/issues/889

**Comment by CatCassie** [comment]
Thanks for the heads up, that's exactly the same issue.

**Comment by CatCassie** [comment]
actually, come to think of it ... maybe we can just escape all the invalid chars instead of fast fail. easier for the user.

**Comment by medb** [comment]
Yes, I think that it will be better to escape, something like this: https://stackoverflow.com/a/12873723/3227693

**Comment by CatCassie** [comment]
Thank you :)

**Comment by CatCassie** [comment]
I found we only need to escape the invalids chars when DB_HIVE_PASSWORD is imported to the xml file which happens in function install_cloud_sql_proxy.

So I added a local variable in function install_cloud_sql_proxy called "db_hive_password_xml_escaped"  so DB_HIVE_PASSWORD will remain the same as the other operations won't need the escaped version.

Does this look not pretty to you, do we prefer to add a function xmlescape for this logic? Currently I am not seeing anything else need this escape logic.
```
  local db_hive_password_xml_escaped
  db_hive_password_xml_escaped=${DB_HIVE_PASSWORD//&/&amp;}
  db_hive_password_xml_escaped=${db_hive_password_xml_escaped//</&lt;}
  db_hive_password_xml_escaped=${db_hive_password_xml_escaped//>/&gt;}
  db_hive_password_xml_escaped=${db_hive_password_xml_escaped//'"'/&quot;}
```

**Comment by medb** [comment]
Yes, this is exactly what we need to fix this issue.

**Comment by CatCassie** [comment]
Thank for your fast response. I am trying to write the integration test but I ran into some issues.

Before writing the python test script, I am trying to run the test locally and manually by creating a password that has invalid chars and encrypt it using kms. But I don't can't make gcs bucket public due to org policy restriction and cluster create command won't accept non "gs://" path. The other option is to upload the updated shell script to  gs://goog-dataproc-initialization-actions-${REGION}/cloud-sql-proxy/. I am not sure if it's safe to do so. 

Do we have a test bucket to use for testing purpose?

**Comment by medb** [comment]
We do not have such buckets, but usually you do not need them, if you will add test and required files to init actions test suite it will be automatically staged during test if file added in the `data` filed in `BUILD` file:
- https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/integration_tests
- https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/cloud-sql-proxy/test_cloud_sql_proxy.py
- https://github.com/GoogleCloudDataproc/initialization-actions/blob/7d0b75a7b1d63bb2eedad134100f20e3d3bdad22/BUILD#L47

But this test may be hard to write because of the required set up, so just a manual verification will suffice.

**Comment by CatCassie** [comment]
Thank you, I will do a manual verification and submit the PR.
