### ISSUE TITLE
Connecting to Livy endpoint remotely

### ISSUE THREAD

**Issue by davesgonechina** [GoogleCloudDataproc/initialization-actions#914]
I've spun up a cluster with [the Livy initialization action](https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/livy) but am unable to access it. If I go to `https://my-cluster.dataproc.googleusercontent.com/livy` it redirects to `http://localhost:8998/ui`, which obviously doesn't work because it is not local. Are there additional steps I'm missing such as opening ports or otherwise allowing external HTTP/S traffic, or configuration in livy.sh to change the domain namespace of Livy? I have been unable to find relevant documentation.

**Comment by Wittline** [comment]
> I've spun up a cluster with [the Livy initialization action](https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/livy) but am unable to access it. If I go to `https://my-cluster.dataproc.googleusercontent.com/livy` it redirects to `http://localhost:8998/ui`, which obviously doesn't work because it is not local. Are there additional steps I'm missing such as opening ports or otherwise allowing external HTTP/S traffic, or configuration in livy.sh to change the domain namespace of Livy? I have been unable to find relevant documentation.

**Did you find a solution?**

**Comment by davesgonechina** [comment]
@Wittline not that I recall, pretty sure I abandoned Livy on this blocker.
