### ISSUE TITLE
Dataproc Cluster creation fails with connectors.sh init action

### ISSUE THREAD

**Issue by KannanMunusamy** [GoogleCloudDataproc/initialization-actions#918]
Hi,
I am using the below for dataproc cluster creations:

```
gcloud dataproc clusters create xxx \
  --project xxx \
  --region europe-west1 \
  --zone europe-west1-b \
  --image-version 2.0-debian10 \
  --subnet xxx \
  --bucket xxx \
  --scopes 'https://www.googleapis.com/auth/cloud-platform' \
  --master-machine-type n1-standard-32 \
  --master-boot-disk-size 500 \
  --num-workers 6 \
  --worker-machine-type n1-standard-8 \
  --worker-boot-disk-size 500 \
  --optional-components JUPYTER \
  --enable-component-gateway \
  --initialization-actions gs://goog-dataproc-initialization-actions-europe-west1/connectors/connectors.sh \
  --initialization-action-timeout=59m \
  --metadata gcs-connector-version=2.2.0,bigquery-connector-version=1.2.0,spark-bigquery-connector-version=0.20.0
```

It ends with the cluster status ERROR. Tried finding the issue but seems nothing I could. Please help in this regard.
And when init actions are removed, the cluster starts fine.

PFA logs
[kannan_dataproc-initialization-script-0_output.txt](https://github.com/GoogleCloudDataproc/initialization-actions/files/6906868/kannan_dataproc-initialization-script-0_output.txt)
[kannan_dataproc-startup-script_output.txt](https://github.com/GoogleCloudDataproc/initialization-actions/files/6906869/kannan_dataproc-startup-script_output.txt)

**Comment by praaxe** [comment]
Hello,

we have the same issue with our cluster : 

`gcloud beta dataproc clusters create cluster-production --bucket xxx --region europe-west1 --subnet default --zone europe-west1-d --master-machine-type n1-standard-4 --master-boot-disk-size 40 --num-workers 4 --worker-machine-type n1-standard-2 --worker-boot-disk-size 40 --image-version 2.0-debian10 --properties dataproc:dataproc.logging.stackdriver.job.driver.enable=true,dataproc:dataproc.logging.stackdriver.enable=true,dataproc:jobs.file-backed-output.enable=true,dataproc:dataproc.logging.stackdriver.job.yarn.container.enable=true --initialization-actions 'gs://xxx/init-actions/gamned-cloud-sql-proxy.sh','gs://goog-dataproc-initialization-actions-europe-west1/connectors/connectors.sh' --metadata gcs-connector-version=2.2.0,bigquery-connector-version=1.2.0,spark-bigquery-connector-version=0.19.1 --project xxx`

We tried removing our script and we still had a timeout.
We tried removing the connector script and the cluster started.

If you have an idea how to resolve this issue...

Thanks

**Comment by praaxe** [comment]
Hello,

We tried changing the metadata to load only the spark-bigquery connector (as we don't need the others) and it worked.

We also saw that google Cloud storage gs://spark-lib/bigquery/ is accessible (with gsutils ls gs://spark-lib/bigquery/) but the other storage gs://hadoop-lib/ return an error 403

**Comment by KannanMunusamy** [comment]
@praaxe Thank you. Great your suggestion helped and the dataproc cluster creation works for me.

**Comment by medb** [comment]
As note
