### ISSUE TITLE
How to add NVMe SSDs on Dataproc?

### ISSUE THREAD

**Issue by HongW2019** [GoogleCloudDataproc/initialization-actions#934]
We are trying to create a Dataproc cluster with local SSDs attached, for better performance we want to specify NVMe interface when adding local SSDs to worker nodes, but there isn't such initialization parameters. The local SSDs will be SCSI interface by default when cluster created.
The overall configuration can be inferred at [Google Guide ](https://cloud.google.com/sdk/gcloud/reference/dataproc/clusters/create)
```
gcloud dataproc clusters create cluster-name \
    --region=region \
    --num-master-local-ssds=1 \
    --num-worker-local-ssds=1 \
    --num-secondary-worker-local-ssds=1 \
    ... other args ...
```

But there is [such a flag](https://cloud.google.com/compute/docs/disks/local-ssd#create_local_ssd) when create compute instances like `--local-ssd interface=`
```
gcloud compute instances create example-instance \
    --machine-type n2-standard-8 \
    --local-ssd interface=[INTERFACE_TYPE] \
    --local-ssd interface=[INTERFACE_TYPE] \
    --image-project [IMAGE_PROJECT] \
    --image-family [IMAGE_FAMILY]
```
So how can we choose NVMe interface when adding Dataproc local SSDs?

**Comment by HongW2019** [comment]
@medb Do you have any idea on such requests? Thanks for you help.

**Comment by medb** [comment]
Please file FR for this in public issue tracker: http://cloud/support/docs/issue-trackers

**Comment by HongW2019** [comment]
> Please file FR for adding support for specifying Local SSD interface in public issue tracker: http://cloud/support/docs/issue-trackers

Thanks. I have submitted an issue https://issuetracker.google.com/issues/200839964
