### ISSUE TITLE
Change default DNS resolver in Dataproc's with Ubuntu image due to inability to resolve .local domains

### ISSUE THREAD

**Issue by Dominos** [GoogleCloudDataproc/initialization-actions#949]
**Problem**
While using Google Dataproc we browse domains with ".local".  Unfortunately default Ubuntu DNS resolver cannot resolve them, while e.g Dataproc with Debian image can. 

Technically, those domains should be migrated to ".lan" - we're unable to do that, so we're looking for a "patch" in Ubuntu image. 

**Possible solution**
Change default DNS resolver to the one from `/run/systemd/resolve/resolv.conf` in the Dataproc's startup:
`ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf`

I've reproduced the problem on my Dataproc and running the command above made DNS server resolve ".local" domains.

**My proposition**
1. Add the _script_ which runs in the Dataproc's startup (or edit the existing if it's in this repository - I can't find it)

Script:
1. Checks the user's operating system
2. If the operating system is Ubuntu - runs given command

**What do I need from you?**
1. Please tell me whether that change is OK
2. If you accept the change - I'd need to know which script in this repository is run in the Dataproc's startup - then I'll be able to submit Pull Request

some knowledge sources: https://askubuntu.com/questions/1068131/ubuntu-18-04-local-domain-dns-lookup-not-working

**Comment by Dominos** [comment]
@medb Hey, may I ask you to take a look for this issue? It's quite important for us.

**Comment by medb** [comment]
I think there is a confusion - init actions are not run at the Dataproc cluster startup by default, these are custom scripts that allow users to customize clusters during startup: http://cloud/dataproc/docs/concepts/configuring-clusters/init-actions

For your issue you either need to write your own init action that makes necessary modifications during Dataproc cluster startup or create a custom Dataproc image that will have necessary modifications out of the box: http://cloud/dataproc/docs/guides/dataproc-images

**Comment by Dominos** [comment]
Hey,
aw, I've misunderstood the whole concept and initialization actions, sorry. 

So, to clarify:
I want to add the script which solves the problem I've described to this repo.
And:
- I wonder whether you find it's a good place for that script (I mean - this repo)
- If so, in which catalog I should add it? I don't see any good place here.

**Comment by medb** [comment]
This seems to be a quite small change (just one line?) and Ubuntu-specific to host in common repo. Is there a reason that you would like to contribute it, instead of using it internally?

**Comment by Dominos** [comment]
Hey,
yeah - it might be one liner script.  

We found this script to be useful to the others too - so that's the main reason why we wanted to contribute it.

**Comment by medb** [comment]
Sorry, but it does not look like maintenance and support cost justify its addition to the common repo.

**Comment by Dominos** [comment]
Okay, thanks for the info!
Bests
