### ISSUE TITLE
Dataproc Install zookeeper latest version on dataproc as zookeeper quorum mode on cluster creation

### ISSUE THREAD

**Issue by mohamedkashifuddin** [GoogleCloudDataproc/initialization-actions#951]
Does anyone know how to install zookeeper latest version on dataproc as zookeeper quorum mode. while cluster creation.

`On latest dataproc version 2.0 (Debian 10, Hadoop 3.2, Spark 3.1)
`

There are two ways to install zookeeper on dataproc one with[ initialization-actions scripts ](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/zookeeper/zookeeper.sh)and another way is just by selecting as **optional-components ZOOKEEPER** while cluster creation.

The problem with both way I m facing is both doesn't install latest version 3.6.3 instead they install version 3.4. For my use-case I need the latest with zookeeper quorum mode.

One weird thing which I notices when I use optional-components ZOOKEEPER it doesn't form zookeeper quorum instead it installs as standalone mode in master and all slave nodes but while using initialization action scripts on cluster creation it does form zookeeper quorum but still its 3.4. only and not latest version 3.6.3 
Is there any way to run this zookeeper initialization-actions scripts on version `On latest dataproc version 2.0 (Debian 10, Hadoop 3.2, Spark 3.1)
`  or is there any other way ?  @medb @szewi @aniket486

**Comment by medb** [comment]
This is not supported, you will need to write your own init script that installs Zookeeper version that you need, of wait on Dataproc 2.1 image release (no ETA yet) that will have a newer Zookeeper version.
