### ISSUE TITLE
Does this initialization action offer the same as latest edition as Google Cloud Marketplace?

### ISSUE THREAD

**Issue by stevenzhang-support** [GoogleCloudDataproc/initialization-actions#957]
I have checked some news about starburst Enterprise edition on Google Cloud and I found that the following information is the most insightful as per [[1]]. It seems to me that the support at least for Latest Edition (version: 360) from Google Cloud to Starburst Presto has migrated from [[2]] to the Google Cloud marketplace as per [[1]]. The good sign of this is that the edition of presto available from the Google Cloud Market is 360 but the edition available from [[2]] is only 332 as per output given in [[3] ].

Since the product has been available in Google Cloud Market therefore I do not think the support will be duplicated from Github. 

**Could Google Dataproc team advise me if the repository in [[2]] will provide the latest edition of Starburst Presto as it does from Google Cloud Marketplace**.

I would like to hear from you after you have reviewed the availability per [[4]] suits your needs or not.

[1]: https://blog.starburst.io/starburst-launches-in-google-cloud-marketplace
[2]: https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/starburst-presto
[3]: https://storage.googleapis.com/starburstdata/presto/332e/332-e.0/presto-server-332-e.0.tar.gz
[4]: https://console.cloud.google.com/marketplace/details/starburst-public/starburst-presto?q=starburst

**Comment by medb** [comment]
No, init action is currently hard coded `332` version:
https://github.com/GoogleCloudDataproc/initialization-actions/blob/25157b4a20e7283c0c7c77f391399c5fa17c46c3/starburst-presto/presto.sh#L25-L26

It's up to Starburst to update this init action to refer newer version, if they want to provide newer Presto version via this init action.

That said, Dataproc supports Presto without this init action: http://cloud/dataproc/docs/concepts/components/presto
