### ISSUE TITLE
master-post-init prevents cluster from entering Running state

### ISSUE THREAD

**Issue by oneextrafact** [GoogleCloudDataproc/initialization-actions#961]
I'm trying to use an adapted version of the master-post-init.sh script as an initialization action. When I do so, the part of the code that checks for the cluster to be in RUNNING state appears to prevent the cluster from actually entering that state, leading to a timeout eventually. I have a feeling that this is because all initialization actions must be complete before the status can change, so effectively we get a deadlock. Is there a way to have a script that is guaranteed to execute when the cluster is RUNNING?

**Comment by medb** [comment]
No, you will need to use `master-post-init.sh` for this, or submit some job (Pig shell script, for example) that will run when cluster is in running state.
