### ISSUE TITLE
No access to PyPI.org

### ISSUE THREAD

**Issue by BusiPlay** [GoogleCloudDataproc/initialization-actions#972]
Spinning up a Private Dataproc cluster in a full private environment with no access to Internet, the https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/python/pip-install.sh script offers no way to specify which PyPI server you use, this defaults to https://pypi.org and Fastly CDN.

Any way to tell initialization actions to use a private PyPI server (eg Google Artifact Registry?)

**Comment by medb** [comment]
No, you will need to modify init action to configure this.
